[workspace]
members = ["aesm-client", "enclave-runner", "fortanix-sgx-tools", "sgx-isa", "sgxs", "sgxs-tools", "fortanix-sgx-abi", "sgxs-loaders"]

[patch.crates-io]
winapi = { git = 'https://github.com/parthsane/winapi-rs', branch="enclaveapi_r"}
